apiVersion: app/v1
kind: Replicas
metadata:
  name: icrm_archer
  labels
    env: production
spec:
  selector:
    matchlabels:
      env: production
  replicas: 9
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
